---
title: "Uge 1"
author: "Christian Præst Møller"
date: "2026-04-27"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
int_arr <- rexp(100,1)
arr <-cumsum(int_arr)

outs <- array(1:2)        

myData=data.frame(x=arr,y=outs)
ggplot(myData, aes(x=x, y=y)) + 
  geom_point()
```

```{r}
simulate_hpp <- function(lambda = 1, T_max = 2) {
  t <- 0
  arrivals <- c()
  
  while (TRUE) {
    t <- t + rexp(1, rate = lambda)
    if (t > T_max) break
    arrivals <- c(arrivals, t)
  }
  
  return(arrivals)
}

arr <- simulate_hpp()
outs <- array(1:length(arr))        

myData=data.frame(x=arr,y=outs)
ggplot(myData, aes(x=x, y=y)) + 
  geom_point()


```
(b)
Nyt 
```{r}
simulate_hpp <- function(lambda = 1, T_max = 2+2^2) {
  t <- 0
  arrivals <- c()
  
  while (TRUE) {
    t <- t + rexp(1, rate = lambda)
    if (t > T_max) break
    arrivals <- c(arrivals, t)
  }
  
  return(arrivals)
}

arr <- simulate_hpp()
outs <- array(1:length(arr))        

myData=data.frame(x=arr,y=outs)
ggplot(myData, aes(x=x, y=y)) + 
  geom_point()

```

